# Generated by Django 5.2.10 on 2026-01-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="Audios",
            field=models.FileField(blank=True, null=True, upload_to="article_audios/"),
        ),
    ]
