# Generated by Django 5.2.10 on 2026-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0002_article_audios"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="Audio_length",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="article",
            name="Audio_size",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
