# Generated by Django 5.2.10 on 2026-01-14 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0003_article_audio_length_article_audio_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="rank",
            field=models.SmallIntegerField(
                choices=[
                    (-8, "rank -8"),
                    (-7, "rank -7"),
                    (-6, "rank -6"),
                    (-5, "rank -5"),
                    (-4, "rank -4"),
                    (-3, "rank -3"),
                    (-2, "rank -2"),
                    (-1, "rank -1"),
                    (0, "rank 0"),
                    (1, "rank 1"),
                    (2, "rank 2"),
                    (3, "rank 3"),
                    (4, "rank 4"),
                    (5, "rank 5"),
                    (6, "rank 6"),
                    (7, "rank 7"),
                    (8, "rank 8"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="rank_points",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-8),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
    ]
