# Generated by Django 5.2.10 on 2026-01-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0004_topic_rank_topic_rank_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trendingtopic",
            name="rank",
        ),
    ]
