# Generated by Django 5.2.10 on 2026-01-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="languageoptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_content", models.TextField()),
                ("translated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Articles.article",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Translate.languageoptions",
                    ),
                ),
            ],
        ),
    ]
