# Generated by Django 5.2.10 on 2026-01-14 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0001_initial"),
        ("Customer", "0001_initial"),
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSuggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("suggested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to_users",
                        to="Articles.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customer.userinfo",
                    ),
                ),
            ],
        ),
    ]
