# Generated by Django 5.2.10 on 2026-01-14 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalistInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totlelikes", models.PositiveIntegerField(default=0)),
                ("totlenewsarticles", models.PositiveIntegerField(default=0)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "rank_points",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-8),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "rank",
                    models.SmallIntegerField(
                        choices=[
                            (-8, "rank -8"),
                            (-7, "rank -7"),
                            (-6, "rank -6"),
                            (-5, "rank -5"),
                            (-4, "rank -4"),
                            (-3, "rank -3"),
                            (-2, "rank -2"),
                            (-1, "rank -1"),
                            (0, "rank 0"),
                            (1, "rank 1"),
                            (2, "rank 2"),
                            (3, "rank 3"),
                            (4, "rank 4"),
                            (5, "rank 5"),
                            (6, "rank 6"),
                            (7, "rank 7"),
                            (8, "rank 8"),
                        ],
                        default=0,
                    ),
                ),
                ("jioing_date", models.DateTimeField(auto_now_add=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
